/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://vdrbsoyxuzfs7ceqmz3jkirbfi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-aifzocgu3rc3rf454rzrmbsw3i",
    "aws_cognito_identity_pool_id": "us-east-1:e74e6d3c-f7ab-4124-b2fa-d89c8825db6a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_r9k88fOfk",
    "aws_user_pools_web_client_id": "3fdin2lvi5eo9pt4tr8lguquvl",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
